import pytest
from unittest.mock import MagicMock, patch
from services.explanation import ExplanationService
from schemas.prediction import InferenceResult

@pytest.fixture
def mock_inference_result():
    return InferenceResult(
        task1_probs=[0.1, 0.9],
        task2_probs=[0.8, 0.2],
        task1_label="PD",
        task2_label="PD",
        windows_analysed=10
    )

def test_explanation_service_success(mock_inference_result):
    """Test that the service returns a generated explanation when the API call succeeds."""
    with patch("google.genai.Client") as mock_client_class:
        mock_client = MagicMock()
        # Mocking a response that satisfies the length requirement (>= 50 chars)
        mock_client.models.generate_content.return_value.text = (
            "This is a detailed medical explanation generated by Gemini. "
            "It explains the Hierarchical Transformer results for the given smartwatch sensor data windows."
        )
        mock_client_class.return_value = mock_client
        
        service = ExplanationService(api_key="fake_key")
        explanation = service.explain(mock_inference_result, "Relaxed")
        
        assert len(explanation) >= 50
        assert "Hierarchical Transformer" in explanation
        mock_client.models.generate_content.assert_called_once()

def test_explanation_service_no_api_key(mock_inference_result):
    """Test that the service returns a fallback explanation when no API key is provided."""
    service = ExplanationService(api_key="")
    explanation = service.explain(mock_inference_result, "Relaxed")
    
    assert "Note: Automatic medical explanation unavailable" in explanation
    assert "Gemini Client not initialized" in explanation

def test_explanation_service_api_error(mock_inference_result):
    """Test that the service returns a fallback explanation when the API call fails."""
    with patch("google.genai.Client") as mock_client_class:
        mock_client = MagicMock()
        mock_client.models.generate_content.side_effect = Exception("API Timeout")
        mock_client_class.return_value = mock_client
        
        service = ExplanationService(api_key="fake_key")
        explanation = service.explain(mock_inference_result, "Relaxed")
        
        assert "Note: Automatic medical explanation unavailable" in explanation
        assert "API Timeout" in explanation

def test_explanation_service_low_confidence_warning():
    """Test that a low-confidence warning is included in the prompt when confidence is < 0.5."""
    low_conf_result = InferenceResult(
        task1_probs=[0.4, 0.4],
        task2_probs=[0.6, 0.4],
        task1_label="PD",
        task2_label="PD",
        windows_analysed=5
    )

    with patch("google.genai.Client") as mock_client_class:
        mock_client = MagicMock()
        mock_client_class.return_value = mock_client
        
        service = ExplanationService(api_key="fake_key")
        service.explain(low_conf_result, "Relaxed")
        
        # Verify that the warning was injected into the prompt
        _, kwargs = mock_client.models.generate_content.call_args
        prompt = kwargs["contents"]
        assert "LOW CONFIDENCE WARNING" in prompt

def test_explanation_service_no_patient_id(mock_inference_result):
    """Test that the constructed prompt does not contain patient identifiers."""
    with patch("google.genai.Client") as mock_client_class:
        mock_client = MagicMock()
        mock_client_class.return_value = mock_client
        
        service = ExplanationService(api_key="fake_key")
        service.explain(mock_inference_result, "Relaxed")
        
        _, kwargs = mock_client.models.generate_content.call_args
        prompt = kwargs["contents"]
        
        # Verify absence of identifiers
        assert "patient_id" not in prompt.lower()
        assert "subject_id" not in prompt.lower()
        assert "patient_name" not in prompt.lower()
