'use client';

import { Sparkles, Loader2 } from 'lucide-react';

interface ExplanationPanelProps {
  explanation: string;
  loading: boolean;
}

export default function ExplanationPanel({ explanation, loading }: ExplanationPanelProps) {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-blue-100 overflow-hidden flex flex-col h-full">
      <div className="bg-blue-50 px-6 py-4 border-b border-blue-100 flex items-center space-x-2">
        <Sparkles className="h-5 w-5 text-blue-600" />
        <h2 className="text-lg font-bold text-blue-900">AI Medical Explanation</h2>
      </div>

      <div className="p-6 flex-grow">
        {loading ? (
          <div className="flex flex-col items-center justify-center h-48 space-y-4">
            <Loader2 className="h-8 w-8 text-blue-600 animate-spin" />
            <p className="text-sm text-gray-500 font-medium">Gemini is interpreting data...</p>
          </div>
        ) : (
          <div className="prose prose-blue max-w-none">
            <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
              {explanation || "Prediction complete. AI interpretation pending..."}
            </p>
          </div>
        )}
      </div>

      <div className="px-6 py-3 bg-gray-50 border-t border-gray-100 italic">
        <p className="text-[10px] text-gray-400">
          Disclaimer: This explanation is generated by Gemini 2.0 and is intended for research purposes.
        </p>
      </div>
    </div>
  );
}
